// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sxvneucqcyeuftupxsdz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN4dm5ldWNxY3lldWZ0dXB4c2R6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyMDQ2NDIsImV4cCI6MjA2MTc4MDY0Mn0.VKWCgZHaXoMm9ddpfo8-avjd1x5vjQ7wj2F9Z1_lz_w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);